const Constants = {
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGOUT: 'USER_LOGOUT',
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIE: 'FETCH_MOVIE',
  SET_MOVIE: 'SET_MOVIE',
  SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
  SEARCH_MOVIES_FAIL: 'SEARCH_MOVIES_FAIL'
};

export default Constants;
